export const siteConfig = {
  name: "Transatlantic University",
  shortName: "TAU",
  officialName: "Transatlantic University of Medicine and Health Sciences",
  tagline: "Advancing Medical Education, Research and Global Healthcare Excellence",
  description:
    "Transatlantic University (TAU) is a private medical institution located in Umuchukwu, Anambra State, Nigeria — founded by Nigerian-American physician and philanthropist Dr. Godwin Maduka.",
  url: "https://tau.edu.ng",
  location: {
    town: "Umuchukwu",
    state: "Anambra State",
    country: "Nigeria",
    address: "Transatlantic University, Umuchukwu, Anambra State, Nigeria",
  },
  contact: {
    phone: "+234 800 TAU MEDS",
    phoneAlt: "+234 700 828 6337",
    email: "admissions@tau.edu.ng",
    emailAlt: "info@tau.edu.ng",
    admissionsEmail: "admissions@tau.edu.ng",
  },
  social: {
    facebook: "https://facebook.com/transatlanticuniversity",
    twitter: "https://x.com/transatlanticuni",
    instagram: "https://instagram.com/transatlanticuniversity",
    linkedin: "https://linkedin.com/school/transatlantic-university",
    youtube: "https://youtube.com/@transatlanticuniversity",
  },
  stats: [
    { value: 12, suffix: "+", label: "Faculties & Schools" },
    { value: 8000, suffix: "+", label: "Students Enrolled" },
    { value: 400, suffix: "+", label: "Academic Staff" },
    { value: 95, suffix: "%", label: "Graduate Success Rate" },
  ],
} as const;

export const route = {
  home: "/",
  about: {
    overview: "/about",
    history: "/about/history",
    mission: "/about/mission-vision",
    leadership: "/leadership",
    governance: "/about/governance",
    accreditations: "/about/accreditations",
    campusMap: "/about/campus-map",
    diversity: "/about/diversity",
    sustainability: "/about/sustainability",
  },
  study: {
    undergraduate: "/undergraduate-programs",
    postgraduate: "/postgraduate",
    faculties: "/faculties",
    departments: "/departments",
    admissions: "/admissions",
    tuition: "/tuition",
    international: "/international",
    studentLife: "/student-life",
  },
  research: {
    overview: "/research",
    centres: "/research/centres",
    publications: "/research/publications",
    funding: "/research/funding",
    innovation: "/research/innovation",
    ethics: "/research/ethics",
  },
  hospital: {
    overview: "/teaching-hospital",
    departments: "/teaching-hospital/departments",
    patientCare: "/teaching-hospital/patient-care",
    findDoctor: "/teaching-hospital/find-a-doctor",
    referrals: "/teaching-hospital/referrals",
    education: "/teaching-hospital/medical-education",
  },
  community: {
    news: "/news",
    events: "/events",
    alumni: "/alumni",
    careers: "/careers",
    library: "/library",
    giving: "/giving",
  },
  contact: "/contact",
  login: "/login",
  apply: "/admissions/apply",
} as const;
